export const url = "http://localhost:3001"
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRIES_NAME = "GET_COUNTRIES_NAME";
export const GET_DETAIL = "GET_DETAIL";
export const FILTER_BY_CONTINENTS = 'FILTER_BY_CONTINENTS';
export const FILTER_BY_ACTIVITY = 'FILTER_BY_ACTIVITY';
export const ORDER_BY_NAME = 'ORDER_BY_NAME'
export const ORDER_BY_POPULATION = 'ORDER_BY_POPULATION'
export const GET_ACTIVITY_CREATED = 'GET_ACTIVITY_CREATED'
export const POST_ACTIVITY = 'POST_ACTIVITY'
export const CLEAR_DETAIL  = 'CLEAR_DETAIL '

